info:
  contact: {}
paths:
  /api/user/CreateUser:
    post:
      consumes:
      - application/json
      description: Create new user
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create new user
      tags:
      - users
  /api/user/RefreshToken:
    post:
      consumes:
      - application/json
      description: Refresh user's token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Refresh user's token
      tags:
      - users
swagger: "2.0"
