import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import Provider from './providers'
import { BgMain } from './styles'

import { clmx } from '@/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <BgMain className={clmx(`overflow-y-hidden max-h-screen`)}>
            {children}
          </BgMain>
        </body>
      </html>
    </Provider>
  )
}
