CREATE TABLE
  IF NOT EXISTS users (
    id VARCHAR PRIMARY KEY NOT NULL UNIQUE,
    fullname VARCHAR NOT NULL DEFAULT '',
    username VARCHAR UNIQUE NOT NULL UNIQUE,
    password VARCHAR NOT NULL
  );