// Code generated by tygo. DO NOT EDIT.

//////////
// source: common.go

export interface ErrorResponse {
  error: string;
}

//////////
// source: products.go

export interface GetProductsInput {
  before: string;
  after: string;
  first: number /* int32 */;
  last: number /* int32 */;
}

//////////
// source: users.go

export interface CreateUserInput {
  fullname: string;
  username: string;
  password: string;
}
export interface LoginAPIInput {
  username: string;
  password: string;
}
export interface LoginAPIResponse {
  success: boolean;
  message: string;
}
